// Generated by gencpp from file crane_x7_examples/ObstacleAvoidanceResponse.msg
// DO NOT EDIT!


#ifndef CRANE_X7_EXAMPLES_MESSAGE_OBSTACLEAVOIDANCERESPONSE_H
#define CRANE_X7_EXAMPLES_MESSAGE_OBSTACLEAVOIDANCERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace crane_x7_examples
{
template <class ContainerAllocator>
struct ObstacleAvoidanceResponse_
{
  typedef ObstacleAvoidanceResponse_<ContainerAllocator> Type;

  ObstacleAvoidanceResponse_()
    : result(false)  {
    }
  ObstacleAvoidanceResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::crane_x7_examples::ObstacleAvoidanceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crane_x7_examples::ObstacleAvoidanceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleAvoidanceResponse_

typedef ::crane_x7_examples::ObstacleAvoidanceResponse_<std::allocator<void> > ObstacleAvoidanceResponse;

typedef boost::shared_ptr< ::crane_x7_examples::ObstacleAvoidanceResponse > ObstacleAvoidanceResponsePtr;
typedef boost::shared_ptr< ::crane_x7_examples::ObstacleAvoidanceResponse const> ObstacleAvoidanceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crane_x7_examples::ObstacleAvoidanceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crane_x7_examples::ObstacleAvoidanceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::crane_x7_examples::ObstacleAvoidanceResponse_<ContainerAllocator1> & lhs, const ::crane_x7_examples::ObstacleAvoidanceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::crane_x7_examples::ObstacleAvoidanceResponse_<ContainerAllocator1> & lhs, const ::crane_x7_examples::ObstacleAvoidanceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace crane_x7_examples

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::crane_x7_examples::ObstacleAvoidanceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crane_x7_examples::ObstacleAvoidanceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crane_x7_examples::ObstacleAvoidanceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crane_x7_examples::ObstacleAvoidanceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crane_x7_examples::ObstacleAvoidanceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crane_x7_examples::ObstacleAvoidanceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crane_x7_examples::ObstacleAvoidanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::crane_x7_examples::ObstacleAvoidanceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::crane_x7_examples::ObstacleAvoidanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crane_x7_examples/ObstacleAvoidanceResponse";
  }

  static const char* value(const ::crane_x7_examples::ObstacleAvoidanceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crane_x7_examples::ObstacleAvoidanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool                        result\n"
"\n"
;
  }

  static const char* value(const ::crane_x7_examples::ObstacleAvoidanceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crane_x7_examples::ObstacleAvoidanceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleAvoidanceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crane_x7_examples::ObstacleAvoidanceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crane_x7_examples::ObstacleAvoidanceResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRANE_X7_EXAMPLES_MESSAGE_OBSTACLEAVOIDANCERESPONSE_H
