// Generated by gencpp from file crane_x7_examples/ObstacleAvoidance.msg
// DO NOT EDIT!


#ifndef CRANE_X7_EXAMPLES_MESSAGE_OBSTACLEAVOIDANCE_H
#define CRANE_X7_EXAMPLES_MESSAGE_OBSTACLEAVOIDANCE_H

#include <ros/service_traits.h>


#include <crane_x7_examples/ObstacleAvoidanceRequest.h>
#include <crane_x7_examples/ObstacleAvoidanceResponse.h>


namespace crane_x7_examples
{

struct ObstacleAvoidance
{

typedef ObstacleAvoidanceRequest Request;
typedef ObstacleAvoidanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ObstacleAvoidance
} // namespace crane_x7_examples


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crane_x7_examples::ObstacleAvoidance > {
  static const char* value()
  {
    return "72c38d661db946d478d0ae7732add5d5";
  }

  static const char* value(const ::crane_x7_examples::ObstacleAvoidance&) { return value(); }
};

template<>
struct DataType< ::crane_x7_examples::ObstacleAvoidance > {
  static const char* value()
  {
    return "crane_x7_examples/ObstacleAvoidance";
  }

  static const char* value(const ::crane_x7_examples::ObstacleAvoidance&) { return value(); }
};


// service_traits::MD5Sum< ::crane_x7_examples::ObstacleAvoidanceRequest> should match
// service_traits::MD5Sum< ::crane_x7_examples::ObstacleAvoidance >
template<>
struct MD5Sum< ::crane_x7_examples::ObstacleAvoidanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crane_x7_examples::ObstacleAvoidance >::value();
  }
  static const char* value(const ::crane_x7_examples::ObstacleAvoidanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crane_x7_examples::ObstacleAvoidanceRequest> should match
// service_traits::DataType< ::crane_x7_examples::ObstacleAvoidance >
template<>
struct DataType< ::crane_x7_examples::ObstacleAvoidanceRequest>
{
  static const char* value()
  {
    return DataType< ::crane_x7_examples::ObstacleAvoidance >::value();
  }
  static const char* value(const ::crane_x7_examples::ObstacleAvoidanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crane_x7_examples::ObstacleAvoidanceResponse> should match
// service_traits::MD5Sum< ::crane_x7_examples::ObstacleAvoidance >
template<>
struct MD5Sum< ::crane_x7_examples::ObstacleAvoidanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crane_x7_examples::ObstacleAvoidance >::value();
  }
  static const char* value(const ::crane_x7_examples::ObstacleAvoidanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crane_x7_examples::ObstacleAvoidanceResponse> should match
// service_traits::DataType< ::crane_x7_examples::ObstacleAvoidance >
template<>
struct DataType< ::crane_x7_examples::ObstacleAvoidanceResponse>
{
  static const char* value()
  {
    return DataType< ::crane_x7_examples::ObstacleAvoidance >::value();
  }
  static const char* value(const ::crane_x7_examples::ObstacleAvoidanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CRANE_X7_EXAMPLES_MESSAGE_OBSTACLEAVOIDANCE_H
